# Generated by Django 5.1 on 2024-08-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
