# Generated by Django 5.1 on 2024-08-19 06:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='shares',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.CheckConstraint(condition=models.Q(('shares__gte', 1)), name='shares_positive'),
        ),
    ]
