# Generated by Django 5.1 on 2024-09-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_history_name_history_new_cash_history_total_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'transacted'], name='api_history_user_id_5d7cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'symbol'], name='api_portfol_user_id_c257e4_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'symbol'], name='api_watchli_user_id_bb8032_idx'),
        ),
    ]
